In [22]:
# 일단 2.2장 Retry

In [ ]:
# pytorch = gpu에서 텐서 조작 및 동적 신경망 구축이 가능한 framework

In [ ]:
tensor = 단일 데이터 형식으로 이루어진 자료들의 다차원 행렬
보통 import torch 하고 torch.tensor(~~) 형태로 사용한다


In [3]:
import torch # gpu를 지원하는 텐서 패키지
import torch.nn # 신경망 구축 및 훈련 패키지
import torch.utils # dataloader 및 기타 utility제공 패키지
import torch.autograd # 자동 미분 패키지
import torch.multiprocessing # 서로다른 프로세스에서 동일한 data(tensor) 에 대한 접근 및 사용 가능

In [7]:
import numpy as np
tt = torch.tensor
x = tt([[1,2] , [3,4]])
print(x)
print(x.numpy()) # tensor to ndarray

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [ ]:
torch.FloatTensor # 32비트의 부동소수점
torch.DoubleTensor # 64 ```
torch.LongTensor # 64   부호있는정수
# 얘네들끼리 연산수행 ㄴㄴ 자료형 같아야함

In [9]:
temp = tt([[1,2] , [3,4]])
print(temp.view(4,1)) # 2x2 행렬 to 4x1
print(temp.view(-1)) # 2x2 to 1차원 vec
print(temp.view(1,-1)) # -1은 (1,?)와 같은 뜻으로 다른 차원으로부터 해당 값을 유추한다는 뜻임. temp의 원소 개수 (2x2 = 4) 를 유지한채
# (1,?)의 형태를 만족해야 하므로 (1,4)가 된다
print(temp.view(-1,1)) # 마찬가지로 (4,1)된다

tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [20]:
xxx = tt([[[1,2,3] , [4,5,6] , [7,8,9]]])
print(xxx.view(-1,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [41]:
import pandas as pd
data = pd.read_csv('C:/Users/qhdms/Desktop/2022_AI_Visual_ICT/PYTORCH_STUDY/car_evaluation.csv')
data.head(10)
data['2.1']
data['low']

0        med
1       high
2        low
3        med
4       high
        ... 
1722     med
1723    high
1724     low
1725     med
1726    high
Name: low, Length: 1727, dtype: object

In [38]:
x = torch.from_numpy(data['2.1'].values).unsqueeze(dim=1).float()

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [ ]:
class Custom_dataset(torch.utils.data.Dataset):
    def __init__(self):
        # 필요한 변수를 선언하고 dataset의 전처리를 해주는 함수
    def __len__(self):
        # dataset의 len = total샘플의 수를 가져오는 함수
    def __getitem(self, index):
        # dataset에서 특정 데이터를 가져오는 함수 (idx번째 데이터를 반환하는 함수 , 이때 반환되는 값은 tensor의 형태를 취해야함)
        

In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def __init__(self, csv_file): # csv_file 파라미터를 통해 dataset을 불러옴
        self.label = pd.read_csv(csv_file)
    def __len__(self): # 전체 dataset의 사이즈 return
        return len(self.label)
    def __ getitem__(self, idx)# 전체 x 와 y데이터 중에 해당 idx번째의 데이터를 가져 옴
        sample = torch.tensor(self.label.iloc[idx , 0:3]).int()
        label = torch.tensor(self.label.iloc[idx , 3]).int()
        return sample, label
    
tensor_dataset = CustomDataset('../covtype.csv') # 이거 용량크니까 이따가 학교가서 다운받으셈..
dataset = DataLoader(tensor_dataset , batch_size = 4 , shuffle = True) # 데이터셋을 torch.utils.data.DataLoader에 파라미터로 전달


###
# 데이터 로더(DataLoader) 객체는 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할때 배치 사이즈 만큼 데이터를 꺼내서 사용함
# 근데 데이터를 미리 잘라놓는게 아니고 내부적으로 iterator에 포함된 idx를 이용해서 배치 사이즈 만큼 데이터를 반환하는거임
# total_dataset -> random mix -> queue에 삽입 -> 반복 -> batch1, 2, ...
###

# which is same as this 
for i, data in enumerate(dataset, 0):
    print(i , end = " ")
    batch = data[0]
    print(batch.size() , batch) 
    # 얘네들도 이따가 dataset 다운 받으면 실행해보셈

In [ ]:
# pytorch에서 제공하는 dataset 사용하기
import torchvision.transforms as tf
mnist_transform = tf.Compose([tf.ToTensor() , tf.Normalize((0.5) , (1.0))]) # 평균 0.5 , 표편 1.0 되도록 data 분포(normalize)조정
from torch