In [22]:
# 일단 2.2장 Retry

In [ ]:
# pytorch = gpu에서 텐서 조작 및 동적 신경망 구축이 가능한 framework

In [ ]:
tensor = 단일 데이터 형식으로 이루어진 자료들의 다차원 행렬
보통 import torch 하고 torch.tensor(~~) 형태로 사용한다


In [3]:
import torch # gpu를 지원하는 텐서 패키지
import torch.nn # 신경망 구축 및 훈련 패키지
import torch.utils # dataloader 및 기타 utility제공 패키지
import torch.autograd # 자동 미분 패키지
import torch.multiprocessing # 서로다른 프로세스에서 동일한 data(tensor) 에 대한 접근 및 사용 가능

In [7]:
import numpy as np
tt = torch.tensor
x = tt([[1,2] , [3,4]])
print(x)
print(x.numpy()) # tensor to ndarray

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [ ]:
torch.FloatTensor # 32비트의 부동소수점
torch.DoubleTensor # 64 ```
torch.LongTensor # 64   부호있는정수
# 얘네들끼리 연산수행 ㄴㄴ 자료형 같아야함

In [9]:
temp = tt([[1,2] , [3,4]])
print(temp.view(4,1)) # 2x2 행렬 to 4x1
print(temp.view(-1)) # 2x2 to 1차원 vec
print(temp.view(1,-1)) # -1은 (1,?)와 같은 뜻으로 다른 차원으로부터 해당 값을 유추한다는 뜻임. temp의 원소 개수 (2x2 = 4) 를 유지한채
# (1,?)의 형태를 만족해야 하므로 (1,4)가 된다
print(temp.view(-1,1)) # 마찬가지로 (4,1)된다

tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [20]:
xxx = tt([[[1,2,3] , [4,5,6] , [7,8,9]]])
print(xxx.view(-1,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [41]:
import pandas as pd
data = pd.read_csv('C:/Users/qhdms/Desktop/2022_AI_Visual_ICT/PYTORCH_STUDY/car_evaluation.csv')
data.head(10)
data['2.1']
data['low']

0        med
1       high
2        low
3        med
4       high
        ... 
1722     med
1723    high
1724     low
1725     med
1726    high
Name: low, Length: 1727, dtype: object

In [38]:
x = torch.from_numpy(data['2.1'].values).unsqueeze(dim=1).float()

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [ ]:
class Custom_dataset(torch.utils.data.Dataset):
    def __init__(self):
        # 필요한 변수를 선언하고 dataset의 전처리를 해주는 함수
    def __len__(self):
        # dataset의 len = total샘플의 수를 가져오는 함수
    def __getitem(self, index):
        # dataset에서 특정 데이터를 가져오는 함수 (idx번째 데이터를 반환하는 함수 , 이때 반환되는 값은 tensor의 형태를 취해야함)
        

In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def